steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/warroom-repo/frontend:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/warroom-repo/frontend:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL'
      - '.'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/warroom-repo/frontend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/warroom-repo/frontend:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'warroom-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/warroom-repo/frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/warroom-repo/frontend:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/warroom-repo/frontend:latest'

substitutions:
  _NEXT_PUBLIC_API_URL: 'https://warroom-backend-410969764896.us-central1.run.app/api'

options:
  logging: CLOUD_LOGGING_ONLY
